### ISSUE TITLE
Integrate changes from the final spec

### ISSUE THREAD

**Issue by tomek-he-him** [studio-b12/array-from#1]
> - Array.from/typedArray.from now calls filter function with two arguments.

http://wiki.ecmascript.org/lib/exe/fetch.php?id=harmony%3Aspecification_drafts&cache=cache&media=harmony:working_draft_ecma-262_edition_6_04-27-14.pdf

**Comment by tomek-he-him** [comment]
The final spec is out as well: http://www.ecma-international.org/ecma-262/6.0/ECMA-262.pdf.

**Comment by tomek-he-him** [comment]
Work is going on in #3 – thanks to this awesome man: @barberboy.

**Comment by JakeChampion** [comment]
I think this can be closed now :-)

**Comment by tomek-he-him** [comment]
Yup! Thanks for the heads up! :+1:
