### ISSUE TITLE
Iterators

### ISSUE THREAD

**Issue by jaspervdg** [studio-b12/array-from#2]
I just tried array-from with the result of Map.prototype.keys(), and it does not seem to work (an empty list is returned). From a brief look at the source code, my guess is that it does not handle iterators, and as far as I understand it should.

**Comment by tomek-he-him** [comment]
Hi, we’ve actually just packaged code from the MDN, which was modeled after revision 22 – quite an old one. The spec for `Array.from` has changed once or twice since and we haven’t yet had the time to update.

Would you be willing to help? :) That’s the fastest way to push things forward.

**Comment by jaspervdg** [comment]
I would be willing, but for now I have other things to do.

**Comment by JakeChampion** [comment]
I think this can be closed as #3 has been merged

**Comment by tomek-he-him** [comment]
Wow, thanks for the cleaning up @JakeChampion!
